Traceback (most recent call last):
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pulp import *

prob = LpProblem('Critical Path Problem', LpMinimize)

p1 = 10
p2 = 2
p3 = 3

s1 = LpVariable('Starting time of job 1', 0, None)
s2 = LpVariable('Starting time of job 2', 0, None)
s3 = LpVariable('Starting time of job 3', 0, None)
Cmax = LpVariable('Completion time of finish job', 0, None)

prob += Cmax + (s1 + s2 + s3)

prob += s3 >= s2 + p2 # job 2 precedes job 3
prob += Cmax >= s1 + p1
prob += Cmax >= s2 + p2
prob += Cmax >= s3 + p3

# solve it
prob.solve()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpulp[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      3[0m prob [38;5;241m=[39m LpProblem([38;5;124m'[39m[38;5;124mCritical Path Problem[39m[38;5;124m'[39m, LpMinimize)
[0;32m      5[0m p1 [38;5;241m=[39m [38;5;241m10[39m

[1;31mModuleNotFoundError[0m: No module named 'pulp'
ModuleNotFoundError: No module named 'pulp'

