Traceback (most recent call last):
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\unerue\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pulp import *

# Define problem
prob = LpProblem(name='Marketing', sense=LpMaximize)

# Create decision variables and non-negative constraint
x1 = LpVariable(name='X1', lowBound=0, upBound=None, cat='Continuous')
x2 = LpVariable(name='X2', lowBound=0, upBound=None, cat='Continuous')
x3 = LpVariable(name='X3', lowBound=0, upBound=None, cat='Continuous')

# Set objective function
prob += 6*x1 + 4*x2 + 7*x3

# Set constraints
prob += 1.0*x1 + 0.8*x2 + 1.5*x3 <= 3000
prob += 1.5*x1 + 2.0*x2 + 3.0*x3 <= 5000
prob += x1 + x2 + x3 <= 3500
prob += x2 >= 500

# Solving problem
prob.solve()
print('Status: {}'.format(LpStatus[prob.status]))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpulp[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[0;32m      3[0m [38;5;66;03m# Define problem[39;00m
[0;32m      4[0m prob [38;5;241m=[39m LpProblem(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mMarketing[39m[38;5;124m'[39m, sense[38;5;241m=[39mLpMaximize)

[1;31mModuleNotFoundError[0m: No module named 'pulp'
ModuleNotFoundError: No module named 'pulp'

