Traceback (most recent call last):
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\unerue\miniconda3\envs\vision\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = plt.figure(figsize=(10, 10))
ax1 = fig.add_subplot(2, 2, 1, projection='3d')
ax2 = fig.add_subplot(2, 2, 2, projection='3d')
ax3 = fig.add_subplot(2, 2, 3, projection='3d')
ax4 = fig.add_subplot(2, 2, 4, projection='3d')
    
plot_freq_spec_3d(fp.fft2(im), ax1)
plot_freq_spec_3d(fp.fft2(im1), ax2)
plot_freq_spec_3d(fp.fft2(im2), ax3)
plot_freq_spec_3d(fp.fft2(im3), ax4)
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [7][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      4[0m ax3 [38;5;241m=[39m fig[38;5;241m.[39madd_subplot([38;5;241m2[39m, [38;5;241m2[39m, [38;5;241m3[39m, projection[38;5;241m=[39m[38;5;124m'[39m[38;5;124m3d[39m[38;5;124m'[39m)
[0;32m      5[0m ax4 [38;5;241m=[39m fig[38;5;241m.[39madd_subplot([38;5;241m2[39m, [38;5;241m2[39m, [38;5;241m4[39m, projection[38;5;241m=[39m[38;5;124m'[39m[38;5;124m3d[39m[38;5;124m'[39m)
[1;32m----> 7[0m plot_freq_spec_3d([43mfp[49m[38;5;241m.[39mfft2(im), ax1)
[0;32m      8[0m plot_freq_spec_3d(fp[38;5;241m.[39mfft2(im1), ax2)
[0;32m      9[0m plot_freq_spec_3d(fp[38;5;241m.[39mfft2(im2), ax3)

[1;31mNameError[0m: name 'fp' is not defined
NameError: name 'fp' is not defined

